### ISSUE TITLE
Issue on network_sum parameter?

### ISSUE THREAD

**Issue by ayak0** [beridel/fast_matched_filter#43]
I found that cc with network_sum = True shows the wrong number. It seems to work when I use loops for stations and components with network_sum = False.

<img width="1660" alt="Screen Shot 2023-01-12 at 3 09 30 PM" src="https://user-images.githubusercontent.com/80324436/212380165-25e9d0f0-9af0-4754-a494-3df357f6c8f3.png">

**Comment by beridel** [comment]
The 0.55 error on the network CC sum is way too big for floating point errors, no...? And those errors don't exist on the individual component correlations.

@ebeauce do you have any idea what's going on?

**Comment by ebeauce** [comment]
I’ll try to look at it asap, but not sure I can before Wednesday.

**Comment by calum-chamberlain** [comment]
Sorry to chime in without knowing everything going on here, but it would be worth checking that the moveouts are correct for this sum. It might be worth checking that `np.argmax(cc[0, :, i, j])` returns the expected moveout for that channel in your loop as well.

**Comment by ebeauce** [comment]
I doubt network_sum=True is faulty since it is the oldest feature that has been used by many people, including myself, for a long time. I have personally never found an unexpected result (but I have to say that I never use normalize="full").

What is the weight matrix? It seems that the comparison is incomplete here because network_sum=True performs the weighted sum and the loop shown here doesn't compute a weighted sum.

EDIT: I didn't read Calum carefully enough, but I think that the issue here is what he's describing. the result of np.argmax(cc[0, :, i, j]) is probably different at different channels. So you are not comparing the same values between the loop and the output of network_sum=True. Here, your loop returns the sum of misaligned cc maxima. For the true comparison, you want to print:
`np.max(np.sum(cc, axis=(2, 3)), axis=1)`
